# Generated by Django 4.2 on 2023-04-09 14:38

from django.db import migrations, models
import user_account.utils


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0004_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, validators=[user_account.utils.validate_bd_number]),
        ),
    ]
