# Generated by Django 4.2 on 2023-04-06 09:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0003_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='placedbid',
            name='bid_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
