# Generated by Django 4.2 on 2023-04-06 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0004_placedbid_bid_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placedbid',
            old_name='bid_date',
            new_name='bid_time',
        ),
    ]
