# Generated by Django 4.0.1 on 2023-04-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0006_placedbid_paid_alter_placedbid_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.URLField(),
        ),
    ]
