# Generated by Django 4.0.1 on 2023-04-08 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0008_product_created_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
    ]
