# Generated by Django 4.2 on 2023-04-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0010_alter_product_ending_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='product',
            name='ending_time',
            field=models.DateTimeField(),
        ),
    ]
