# Generated by Django 4.2 on 2023-04-08 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0011_remove_product_start_time_alter_product_ending_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placedbid',
            name='own',
        ),
        migrations.RemoveField(
            model_name='product',
            name='active',
        ),
    ]
