# Generated by Django 4.2 on 2023-04-09 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0012_remove_placedbid_own_remove_product_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
