# Generated by Django 4.2 on 2023-04-09 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0013_product_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='placedbid',
            name='own',
            field=models.BooleanField(default=False),
        ),
    ]
