# Generated by Django 4.2 on 2023-04-09 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0015_product_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='finished',
        ),
    ]
