# Generated by Django 4.2 on 2023-04-09 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0016_remove_product_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placedbid',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='bidding.product'),
        ),
    ]
