# Generated by Django 4.2 on 2023-04-09 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0017_alter_placedbid_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id']},
        ),
    ]
