# Generated by Django 4.2 on 2023-04-09 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0018_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placedbid',
            options={'ordering': ['-amount']},
        ),
    ]
